### ISSUE TITLE
Image bank for the front and back of the fortune cards

### ISSUE THREAD

**Issue by prashasthk** [cse110-sp23-group23/Zoltar#29]
Requirement Description:
- Have a bank of images for the front and back of the fortune cards to randomly pick from when displaying a new fortune card

Any key challenges:
- Find/generate new images

Steps to Implementing:
- Find images online that fit our theme and include in assets
- Implement a function to randomly pick from the image bank

**Comment by Luke-Sheltraw** [comment]
back done; front pending
