### ISSUE TITLE
Ticket Display

### ISSUE THREAD

**Issue by MarcBaeuerle** [cse110-sp23-group23/Zoltar#3]
Requirement Description:
- Implement ticket display functionality as a pop-up screen.

Any key challenges:
- The ticket will be linked with the response generated. 

Steps to Implementing:
- Create an element that is hidden.
- Add response to element
- Include an x button, esc, to close the popup

Other:
- Could use <dialog>

**Comment by LukeSkerrett** [comment]
implemented with escape button.
