### ISSUE TITLE
Add settings menu

### ISSUE THREAD

**Issue by AAP127** [cse110-sp23-group23/Zoltar#35]
**Is your feature request related to a problem? Please describe.**
We would like a clear and concise way to access settings, including mute and program controls.

Possible solutions:
Solution unclear, considering multiple alternatives:
- Separate element on HUD for settings
- Second splash screen to explain controls (fade from red to black, controls fade in to screen with white line going around box as timer.  Also another line below telling user the press spacebar to skip splash screen)
- Escape to access menu
- Some combination of above

**Comment by air-wickvu** [comment]
I can try to do the 2d version
