### ISSUE TITLE
Controls Overlay Before Model

### ISSUE THREAD

**Issue by LukeSkerrett** [cse110-sp23-group23/Zoltar#36]
**Is your feature request related to a problem? Please describe.**
Users do not know the controls of the application.

**Describe the solution you'd like**
After loading screen, activate a splash screen displaying the controls for operating the website. The splash screen will have a timer attached (hour glass / loading ball) that will have the controls fade out after 10 seconds. 

**Describe alternatives you've considered**
Settings display with controls ... 

**Additional context**
n/a

**Comment by Luke-Sheltraw** [comment]
completed
