### ISSUE TITLE
Loading Screen Time Expiration

### ISSUE THREAD

**Issue by LukeSkerrett** [cse110-sp23-group23/Zoltar#5]
Requirement Description:
- Implement a time expiration feature that will redirect to the 2D version if the 3D version is not loaded within 2 minutes. 

Any key challenges:
- Figuring out a latency time to load the alternative application.
- How to handle single threading.

Steps to Implementing:
- ... 

Other:
-

**Comment by Luke-Sheltraw** [comment]
Instead of automatic redirect, something like gmail's loading screen

"Hey, it's taking a while to load. Click [here] to use a 2D (faster) version." 

or something of the sort

**Comment by LukeSkerrett** [comment]
I agree, how would that work since JS is single threaded? would you have to use async ?? (from someone who has never used js before 110.) @Luke-Sheltraw
