### ISSUE TITLE
2D Ticket History Text Overflows on Small Screens

### ISSUE THREAD

**Issue by AAP127** [cse110-sp23-group23/Zoltar#58]
**Describe the bug**
When resizing the window of the 2D version, card text will overflow past the card boundaries.

**To Reproduce**
1. Go to https://zoltar.live/twodee
2. Resize window/ open console

**Expected behavior**
Entire card should maintain its shape like in the 3d version: 
![image](https://github.com/cse110-sp23-group23/Zoltar/assets/92289585/56e4dad4-25dc-4755-9d97-b0ee29c2e24e)

**Screenshots**
![image](https://github.com/cse110-sp23-group23/Zoltar/assets/92289585/c1365777-de6b-4fb0-a72c-7938dce10e54)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox

**Comment by MarcBaeuerle** [comment]
Fixed
