### ISSUE TITLE
Audio fade in not consistent

### ISSUE THREAD

**Issue by RunpengJ** [cse110-sp23-group23/Zoltar#6]
**Describe the bug**
After pressing any key to start, the audio sometimes fades in but sometimes does not .

**To Reproduce**
Need to figure out.

**Expected behavior**
After pressing a key to start, the audio (background music) fades in gradually.

**Screenshots**
No applicable.

**Desktop (please complete the following information):**

**Smartphone if applicable (please complete the following information):**
Not applicable

**Additional context**
May need to look inside the code, or modify the original audio file.

**Comment by Luke-Sheltraw** [comment]
this seems to have been fixed, i.e. no longer reproducable
