### ISSUE TITLE
Find and Implement Zoltar sayings

### ISSUE THREAD

**Issue by AAP127** [cse110-sp23-group23/Zoltar#7]
**Is your feature request related to a problem? Please describe.**
I think the experience of fortune generation would be better if Zoltar spoke; it would feel more interactive.

**Describe the solution you'd like**
I want Zoltar to prompt me to generate my fortune, and interact with me generally. This would ideally be done with reaslitic sounding voices, but may begin with text-to-speech.

**Describe alternatives you've considered**
-Text to speech
-Taking existing voice lines from Zoltar machines
-AI generated voice lines 

**Example Voice lines**
“Click the button, if you dare hear your future”
“What are you waiting for? Flip the card!”
“Ha ha ha ha…”
“I am Zoltar! Speaker of the truth!”

**Comment by AAP127** [comment]
Voice lines added. Function to randomly pick remaining.

**Comment by Luke-Sheltraw** [comment]
done for now
