### ISSUE TITLE
3D: Add button or other input type to prompt fortune generation

### ISSUE THREAD

**Issue by AAP127** [cse110-sp23-group23/Zoltar#8]
**Is your feature request related to a problem? Please describe.**
The usage of the spacebar to generate a fortune is not as intuitive as a user may expect.

**Describe the solution you'd like**
A button, lever, or some other medium of prompting a function should be created. The type of input should be thematically appropriate with the Zoltar machine, and also should be obvious/ intuitive to a user.

**Comment by AAP127** [comment]
Button has been removed in newest release of site. May be converted to an on-machine button vs one that is part of the camera HUD (aka may transition into a statically positioned object on the machine).

**Comment by AAP127** [comment]
Reopened

**Comment by prashasthk** [comment]
> Button has been removed in newest release of site. May be converted to an on-machine button vs one that is part of the camera HUD (aka may transition into a statically positioned object on the machine).

I like this idea, only thing I wanna make sure is that the user is able to find the button easily so that they are not confused as to what to do when they first open the main page

**Comment by Luke-Sheltraw** [comment]
done (see other parallel issue)
